version: '3'
services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8080:8080"
  
  plan_deportivo:
    build: ./plan_deportivo
    ports:
      - "5000:5000"

  deportistas:
    build: ./deportistas
    ports:
      - "5002:5002"
  
  monitor_service:
    build: ./monitor_service
    volumes:
      - ./monitor_service:/app
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
